package es.cecabank.ealiaapp.accesobd.model;

// Generated 12-feb-2016 14:01:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EalEntisAplicaciones generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "EAL_ENTIS_APLICACIONES")
public class EalEntisAplicaciones implements java.io.Serializable {

	private String codAplicacion;
	private EalEntisEntidades ealEntisEntidades;
	private String desAplicacion;
	private String fechaHoraAlta;
	private String fechaHoraBaja;
	private String codTipoAcceso;
	private String claveCifrado;
	private Set<EappSvcsServicios> eappSvcsServicioses = new HashSet<EappSvcsServicios>(0);
	private Set<EappDispInstalaciones> eappDispInstalacioneses = new HashSet<EappDispInstalaciones>(0);
	private Set<EalEntisAppsParam> ealEntisAppsParams = new HashSet<EalEntisAppsParam>(0);

	public EalEntisAplicaciones() {
	}

	public EalEntisAplicaciones(String codAplicacion, EalEntisEntidades ealEntisEntidades, String desAplicacion, String fechaHoraAlta, String codTipoAcceso) {
		this.codAplicacion = codAplicacion;
		this.ealEntisEntidades = ealEntisEntidades;
		this.desAplicacion = desAplicacion;
		this.fechaHoraAlta = fechaHoraAlta;
		this.codTipoAcceso = codTipoAcceso;
	}

	public EalEntisAplicaciones(String codAplicacion, EalEntisEntidades ealEntisEntidades, String desAplicacion, String fechaHoraAlta, String fechaHoraBaja, String codTipoAcceso, String claveCifrado, Set<EappSvcsServicios> eappSvcsServicioses, Set eappDispInstalacioneses, Set ealEntisAppsParams) {
		this.codAplicacion = codAplicacion;
		this.ealEntisEntidades = ealEntisEntidades;
		this.desAplicacion = desAplicacion;
		this.fechaHoraAlta = fechaHoraAlta;
		this.fechaHoraBaja = fechaHoraBaja;
		this.codTipoAcceso = codTipoAcceso;
		this.claveCifrado = claveCifrado;
		this.eappSvcsServicioses = eappSvcsServicioses;
		this.eappDispInstalacioneses = eappDispInstalacioneses;
		this.ealEntisAppsParams = ealEntisAppsParams;
	}

	@Id
	@Column(name = "COD_APLICACION", unique = true, nullable = false, length = 3)
	public String getCodAplicacion() {
		return this.codAplicacion;
	}

	public void setCodAplicacion(String codAplicacion) {
		this.codAplicacion = codAplicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BIC_ENTIDAD", nullable = false)
	public EalEntisEntidades getEalEntisEntidades() {
		return this.ealEntisEntidades;
	}

	public void setEalEntisEntidades(EalEntisEntidades ealEntisEntidades) {
		this.ealEntisEntidades = ealEntisEntidades;
	}

	@Column(name = "DES_APLICACION", nullable = false, length = 50)
	public String getDesAplicacion() {
		return this.desAplicacion;
	}

	public void setDesAplicacion(String desAplicacion) {
		this.desAplicacion = desAplicacion;
	}

	@Column(name = "FECHA_HORA_ALTA", nullable = false, length = 16)
	public String getFechaHoraAlta() {
		return this.fechaHoraAlta;
	}

	public void setFechaHoraAlta(String fechaHoraAlta) {
		this.fechaHoraAlta = fechaHoraAlta;
	}

	@Column(name = "FECHA_HORA_BAJA", length = 16)
	public String getFechaHoraBaja() {
		return this.fechaHoraBaja;
	}

	public void setFechaHoraBaja(String fechaHoraBaja) {
		this.fechaHoraBaja = fechaHoraBaja;
	}

	@Column(name = "COD_TIPO_ACCESO", nullable = false, length = 4)
	public String getCodTipoAcceso() {
		return this.codTipoAcceso;
	}

	public void setCodTipoAcceso(String codTipoAcceso) {
		this.codTipoAcceso = codTipoAcceso;
	}

	@Column(name = "CLAVE_CIFRADO", length = 50)
	public String getClaveCifrado() {
		return this.claveCifrado;
	}

	public void setClaveCifrado(String claveCifrado) {
		this.claveCifrado = claveCifrado;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "EAPP_SVCS_APPS", joinColumns = { @JoinColumn(name = "COD_APLICACION", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "NOMBRE_SERVICIO", nullable = false, updatable = false) })
	public Set<EappSvcsServicios> getEappSvcsServicioses() {
		return this.eappSvcsServicioses;
	}

	public void setEappSvcsServicioses(Set<EappSvcsServicios> eappSvcsServicioses) {
		this.eappSvcsServicioses = eappSvcsServicioses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ealEntisAplicaciones")
	public Set<EappDispInstalaciones> getEappDispInstalacioneses() {
		return this.eappDispInstalacioneses;
	}

	public void setEappDispInstalacioneses(Set<EappDispInstalaciones> eappDispInstalacioneses) {
		this.eappDispInstalacioneses = eappDispInstalacioneses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ealEntisAplicaciones")
	public Set<EalEntisAppsParam> getEalEntisAppsParams() {
		return this.ealEntisAppsParams;
	}

	public void setEalEntisAppsParams(Set<EalEntisAppsParam> ealEntisAppsParams) {
		this.ealEntisAppsParams = ealEntisAppsParams;
	}

}
