package es.cecabank.ealiaapp.accesobd.model;
// default package
// Generated 19-feb-2016 8:48:24 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EalEntisAppsParamId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class EalEntisAppsParamId implements java.io.Serializable {

	private String idParametro;
	private String codAplicacion;

	public EalEntisAppsParamId() {
	}

	public EalEntisAppsParamId(String idParametro, String codAplicacion) {
		this.idParametro = idParametro;
		this.codAplicacion = codAplicacion;
	}

	@Column(name = "ID_PARAMETRO", nullable = false, length = 50)
	public String getIdParametro() {
		return this.idParametro;
	}

	public void setIdParametro(String idParametro) {
		this.idParametro = idParametro;
	}

	@Column(name = "COD_APLICACION", nullable = false, length = 3)
	public String getCodAplicacion() {
		return this.codAplicacion;
	}

	public void setCodAplicacion(String codAplicacion) {
		this.codAplicacion = codAplicacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EalEntisAppsParamId))
			return false;
		EalEntisAppsParamId castOther = (EalEntisAppsParamId) other;

		return ((this.getIdParametro() == castOther.getIdParametro()) || (this.getIdParametro() != null
				&& castOther.getIdParametro() != null && this.getIdParametro().equals(castOther.getIdParametro())))
				&& ((this.getCodAplicacion() == castOther.getCodAplicacion()) || (this.getCodAplicacion() != null
						&& castOther.getCodAplicacion() != null && this.getCodAplicacion().equals(
						castOther.getCodAplicacion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdParametro() == null ? 0 : this.getIdParametro().hashCode());
		result = 37 * result + (getCodAplicacion() == null ? 0 : this.getCodAplicacion().hashCode());
		return result;
	}

}
