
package es.cecabank.ealiaapp.accesobd.model;
// default package
// Generated 19-feb-2016 8:48:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EalEntisAppsParamEsts generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "EAL_ENTIS_APPS_PARAM_ESTS")
public class EalEntisAppsParamEsts implements java.io.Serializable {

	private String codEstado;
	private String desEstado;
	private Set<EalEntisAppsParam> ealEntisAppsParams = new HashSet<EalEntisAppsParam>(0);

	public EalEntisAppsParamEsts() {
	}

	public EalEntisAppsParamEsts(String codEstado, String desEstado) {
		this.codEstado = codEstado;
		this.desEstado = desEstado;
	}

	public EalEntisAppsParamEsts(String codEstado, String desEstado, Set<EalEntisAppsParam> ealEntisAppsParams) {
		this.codEstado = codEstado;
		this.desEstado = desEstado;
		this.ealEntisAppsParams = ealEntisAppsParams;
	}

	@Id
	@Column(name = "COD_ESTADO", unique = true, nullable = false, length = 4)
	public String getCodEstado() {
		return this.codEstado;
	}

	public void setCodEstado(String codEstado) {
		this.codEstado = codEstado;
	}

	@Column(name = "DES_ESTADO", nullable = false, length = 50)
	public String getDesEstado() {
		return this.desEstado;
	}

	public void setDesEstado(String desEstado) {
		this.desEstado = desEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ealEntisAppsParamEsts")
	public Set<EalEntisAppsParam> getEalEntisAppsParams() {
		return this.ealEntisAppsParams;
	}

	public void setEalEntisAppsParams(Set<EalEntisAppsParam> ealEntisAppsParams) {
		this.ealEntisAppsParams = ealEntisAppsParams;
	}

}
